### ISSUE TITLE
一个关于gen_nccl_ops.nccl_all_reduce的问题

### ISSUE THREAD

**Issue by stillwaterman** [jianlong-yuan/syncbn-tensorflow#4]
您好，感谢分享syncbn-tensorflow，但是我在使用时遇到了一个错误。
ValueError: Op type not registered 'NcclAllReduce' in binary running on STILLWATER. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
环境是tf1.12 windows10,我用的时候是用Keras一个自定义层把这个tf函数封装了一下，请问这是由什么原因引起的呢

**Comment by jianlong-yuan** [comment]
this version does not support tf1.12

**Comment by stillwaterman** [comment]
Ok, I have changed to TF1.8, that error disappeared，but have another problem which happend in `if int(outputs.device[-1]) == 0:`. Error message: IndexError: string index out of range. This is because outputs.device[-1] is empty string. Any suggestion?
Does it only work for tf1.7? I think your code is a part of implementation of tensorpack did, do we need special trainer like tensorpack did?

**Comment by jianlong-yuan** [comment]
i just test by tf1.7 . We don't need tensorpack. you can check outputs.device

**Comment by math-yyj** [comment]
> this version does not support tf1.12

and don't support tf1.10, either?

**Comment by stillwaterman** [comment]
@mathyyj Yes, It don't support tf1.10  either, you can use this code `                try:
                    from tensorflow.contrib.nccl.python.ops.nccl_ops import _validate_and_load_nccl_so
                except Exception:
                    pass
                else:
                    _validate_and_load_nccl_so()
                from tensorflow.contrib.nccl.ops import gen_nccl_ops` to avoid first error I met in tf1.10, but I can get over with second error.

**Comment by jianlong-yuan** [comment]
int(outputs.device[-1]) == 0:  It is used to determine when to calculate moving mean and moving variance. In the tensorpack, the method of judgment is more difficult. So you can chose an easy judgment like my code. If this judgment is not suit for you, you can print outputs.device and chose the judgment.
